---
apiVersion: v1
kind: Service
metadata:
  name: crypto-dash
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    role: crypto-dash
  type: LoadBalancer
